### ISSUE TITLE
numba cuda cleanup error message (but no actual failure)

### ISSUE THREAD

**Issue by jllanfranchi** [IceCubeOpenSource/pisa#315]
After running a pipeline employing `reco.vbwkde`, the following error message is output at the very end of the script, just prior to exit (the run completes successfully, so this is not a critical bug as far as I can tell; could cause issues on GPU, though...)

This occurs for single or multi-threaded runs, but _only_ when running with `PISA_FTYPE=fp32`
```
Traceback (most recent call last):
  File "/home/justin/anaconda2/lib/python2.7/site-packages/numba/utils.py", line 647, in _exitfunc
    f()
  File "/home/justin/anaconda2/lib/python2.7/site-packages/numba/utils.py", line 571, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/justin/anaconda2/lib/python2.7/site-packages/numba/cuda/cudadrv/driver.py", line 866, in core
    dealloc.add_item(module_unload, handle)
  File "/home/justin/anaconda2/lib/python2.7/site-packages/numba/cuda/cudadrv/driver.py", line 491, in add_item
    self.clear()
  File "/home/justin/anaconda2/lib/python2.7/site-packages/numba/cuda/cudadrv/driver.py", line 502, in clear
    dtor(handle)
  File "/home/justin/anaconda2/lib/python2.7/site-packages/numba/cuda/cudadrv/driver.py", line 259, in safe_cuda_api_call
    self._check_error(fname, retcode)
  File "/home/justin/anaconda2/lib/python2.7/site-packages/numba/cuda/cudadrv/driver.py", line 296, in _check_error
    raise CudaAPIError(retcode, msg)
numba.cuda.cudadrv.driver.CudaAPIError: [1] Call to cuMemFree results in CUDA_ERROR_INVALID_VALUE
```

**Comment by jllanfranchi** [comment]
I haven't seen this in a long time, may well be an issue with an older numba / cuda / etc., so closing.
