### ISSUE TITLE
pi_earth_absorption unit test fails (numba guvectorize with np.dot)

### ISSUE THREAD

**Issue by jllanfranchi** [IceCubeOpenSource/pisa#550]
Python 3.7.3, numba 0.45.1

```
$ /home/justin/src/pisa/pisa/stages/absorption/pi_earth_absorption.py
<< PISA is running in double precision (FP64) mode; numba is running on GPU >>
Traceback (most recent call last):
  File "/home/justin/src/pisa/pisa_tests/../pisa/stages/absorption/pi_earth_absorption.py", line 219, in <module>
    @guvectorize(signatures, '(n),(n)->()', target=TARGET)
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/npyufunc/decorators.py", line 179, in wrap
    guvec.add(fty)
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/npyufunc/deviceufunc.py", line 475, in add
    glbls = self._get_globals(sig)
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/cuda/vectorizers.py", line 62, in _get_globals
    corefn = cuda.jit(sig, device=True)(self.pyfunc)
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/cuda/decorators.py", line 104, in device_jit
    debug=debug)
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/cuda/compiler.py", line 190, in compile_device
    return DeviceFunction(pyfunc, return_type, args, inline=True, debug=False)
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/cuda/compiler.py", line 221, in __init__
    debug=self.debug, inline=self.inline)
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/cuda/compiler.py", line 51, in compile_cuda
    locals={})
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/compiler.py", line 972, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/compiler.py", line 390, in compile_extra
    return self._compile_bytecode()
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/compiler.py", line 903, in _compile_bytecode
    return self._compile_core()
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/compiler.py", line 890, in _compile_core
    res = pm.run(self.status)
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/compiler.py", line 266, in run
    raise patched_exception
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/compiler.py", line 257, in run
    stage()
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/compiler.py", line 515, in stage_nopython_frontend
    self.locals)
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/compiler.py", line 1124, in type_inference_stage
    infer.propagate()
  File "/home/justin/anaconda2/lib/python3.7/site-packages/numba/typeinfer.py", line 927, in propagate
    raise errors[0]
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Use of unsupported NumPy function 'numpy.dot' or unsupported use of the function.

File "pisa/stages/absorption/pi_earth_absorption.py", line 234:
def calculate_integrated_rho(layer_dists, layer_densities, out):
    <source elided>
    """
    out[0] = np.dot(layer_dists, layer_densities)*1e5 #distances are converted from km to cm
    ^

[1] During: typing of get attribute at /home/justin/src/pisa/pisa_tests/../pisa/stages/absorption/pi_earth_absorption.py (234)

File "pisa/stages/absorption/pi_earth_absorption.py", line 234:
def calculate_integrated_rho(layer_dists, layer_densities, out):
    <source elided>
    """
    out[0] = np.dot(layer_dists, layer_densities)*1e5 #distances are converted from km to cm
    ^
```

**Comment by atrettin** [comment]
Fixed with PR #605
